### PR TITLE
Bumping sensu-plugin version

### PR DESCRIPTION
**Pull request by asachs01**
## Pull Request Checklist

**Is this in reference to an existing issue?**
#78 , #45 

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
See details in #78 . Handler does its own filtering. Bumping up the gem resolves this. 

#### Known Compatibility Issues
This is bumping up to 2.X, likely a breaking change.

### CODE REVIEW

**Comment by cwjohnston** [comment]
Closes #78

**Comment by asachs01** [comment]
@majormoses can I get a 👍/👎 on this?

**Comment by majormoses** [comment]
needs a changelog entry explaining the breaking changes but otherwise looks good. You can look at: https://github.com/sensu-plugins/sensu-plugins-docker/commit/7ce5ba9c782c6f9c37a199b94b21ec92f81264e6for refrence.

**Comment by majormoses** [comment]
I can do that and get it released this weekend.

**Comment by majormoses** [comment]
Looks like travis is clogged up but I cut a release. I will check back later and manually cut a rubygems release if it has not done it by then.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-mailer/versions/3.0.0

**Pull request merged**
